### ISSUE TITLE
Roundcube 1.6 Support?

### ISSUE THREAD

**Issue by SKB-CGN** [alexandregz/twofactor_gauthenticator#170] opened 2022-10-25 05:55 UTC
Hi,
I just upgraded to 1.6 but the plugin is not displayed anymore.

Is there a way to activate it again?

Thanks!

**Comment by umsmin** [comment] 2022-12-23 12:31
I removed it and copied it again into the plugins folder. I only had problems to scan the QR-Code bit I added it manually and it works.

**Comment by schickel007** [comment] 2023-04-21 10:31
I activated the plugin with roundcube 1.6.1 but it does not appear and it not working. try new installation of rc but also this plugin don't want to work. is there really a support for rc 1.6?

**Comment by gabrielt** [comment] 2023-04-23 18:27
Yes, it works with RC 1.6 series. The issue is that the default config.inc.php comes with the author's email addresses in the $rcmail_config['users_allowed_2FA'] variable. Since our email address is different, the plugin isn't displayed inside RC.

To fix this, edit /plugins/twofactor_gauthenticator/config.inc.php and change this setting to:
$rcmail_config['users_allowed_2FA'] = true;

**Comment by schickel007** [comment] 2023-04-24 07:01
With this setting users_allowed_2FA=true plugin still not appear in the setting. 

Somehow the plugin is also not listed as "installed" even it is listed in the plugin section in the main-config of roundcube:

// List of active plugins (in plugins/ directory)

$config['plugins'] = [
        'jqueryui',
        'markasjunk',
        'twofactor_gauthenticator',
];

![image](https://user-images.githubusercontent.com/2758522/233920310-af09e115-376d-44fa-934d-85937917d29b.png)

No clue what's missing...

**Comment by schickel007** [comment] 2023-04-24 09:13
Test it in the past and now also - nothing changed. Also permissions and ownership from the plugin-directory is as requested. Also different variations of "users_allowed_2FA". I also try with fresh "installation" of roundcube.

**Comment by gabrielt** [comment] 2023-04-24 10:37
Take a look at the Rouncube error log file, it might give you a clue there.

**Comment by gabrielt** [comment] 2023-04-24 12:30
Probably something cache-related.

**Comment by ulab** [comment] 2024-02-09 10:10
If this is fixed, close the issue perhaps?

**Comment by lpalgarvio** [comment] 2024-05-11 04:43
works for me using the simple boolean true
`$rcmail_config['users_allowed_2FA'] = true;`

**Closed** 2024-05-11 10:46 UTC
